"""Change column data type

Revision ID: 4f8610244415
Revises: 
Create Date: 2021-05-28 00:47:49.164069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f8610244415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
                    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('firm', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('work', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=True),
                    sa.Column('deal', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('deal_date', sa.DATE(), autoincrement=False, nullable=True),
                    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('insert_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('uid', name='task_pkey')
                    )
    op.create_index('ix_task_work_date', 'task', ['work_date'], unique=False)
    op.create_index('ix_task_deal', 'task', ['deal'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    pass